config/routes.rb
AMT::Application.routes.draw do

  get "amt_comments/index"
  get "priorities/index"

  root 'dashboard#index'

  resources :priorities  do
    resources :dimentions
  end

  resources :dimentions
  resources :factors

  resources :companies, except: [:show,:destroy]

  resources :amt_types do 
    resources :technologies, except: [:index]
  end 

  resources :technologies, only: [:index]

   resources :amt_comments 

end

app/models/amt_comment.rb
class AmtComment < ActiveRecord::Base
  belongs_to :technology
  belongs_to :user
end

app/models/amt_type.rb
class AmtType < ActiveRecord::Base
  validates_presence_of :title
  accepts_nested_attributes_for :technologies
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates_presence_of :name , :city
end

app/models/dimention.rb
class Dimention < ActiveRecord::Base
  belongs_to :priority
  has_many :factors
  validates_presence_of :title, :weight
  validates_numericality_of :weight, greater_than_or_equal_to: 0

  accepts_nested_attributes_for :factors

  def getId
    self.id
  end
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  belongs_to :dimention
  has_many :technologies



  accepts_nested_attributes_for :technologies

end

app/models/factor_survey_result.rb
class FactorSurveyResult < ActiveRecord::Base
  belongs_to :factor
  belongs_to :survey_result
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :dimentions
  validates_presence_of :title, :weight
  validates_numericality_of :weight, greater_than_or_equal_to: 0, less_than_or_equal_to: 100

  accepts_nested_attributes_for :dimentions



  

end

app/models/survey_result.rb
class SurveyResult < ActiveRecord::Base
  belongs_to :company
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates_presence_of :title ,:weight, :description, :benefits
  validates :summary, length: { maximum: 140 }

  belongs_to :factor
  belongs_to :amt_type
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :company
end

app/controllers/amt_types_controller.rb
class AmtTypesController < ApplicationController
  def index
    @amt_types = AmtType.order(:title)
  end

  def new
     @amt_types = AmtType.new
  end

  def create
    @amt_types = AmtType.new(amt_types_params)

    if @amt_types.save
      redirect_to amt_types_path, 
        flash: {notice: "AmtType successfully added"}
    else
      render :new
    end
  end

  def edit
    @amt_types = AmtType.find(params[:id])
  end

  def update
    @amt_types = AmtType.find(params[:id])

    if @amt_types.update(amt_types_params)
      redirect_to amt_types_path, 
        flash: {notice: "AmtType successfully edited"}
    else
      render :edit
    end
  end

  def show
    @amt_types = AmtType.find(params[:id])
  end

  private

    def amt_types_params
      params.require(:amt_type).permit!
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.order(:name)
  end

  def new
     @companies = Company.new
  end

  def create
    @companies = Company.new(companies_params)

    if @companies.save
      redirect_to companies_path, 
        flash: {notice: "Company successfully added"}
    else
      render :new
    end
  end

  def edit
    @companies = Company.find(params[:id])
  end

  def update
    @companies = Company.find(params[:id])

    if @companies.update(companies_params)
      redirect_to companies_path, 
        flash: {notice: "Company successfully edited"}
    else
      render :edit
    end
  end

  private

    def companies_params
      params.require(:company).permit!
    end
end

app/controllers/dimentions_controller.rb
class DimentionsController < ApplicationController

  def index

    @dimentions = Dimention.includes(:priority).order(priority_id: :asc ,weight: :desc)

    if params[:keyword].present?
      q = params[:keyword]
      @dimentions = @dimentions.joins(:priority)
        .where("priorities.title LIKE '%#{q}%' OR dimentions.title LIKE '%#{q}%'")
    end

    if request.xhr?
      render partial: "table", locals: {dimentions: @dimentions}
    end


  end

  def new
    @dimention = Dimention.new
  end

  def create
    @dimention = Dimention.new(dimentions_params)

    if @dimention.save
      redirect_to dimentions_path,
        flash: {notice: "Priority successfully added"}
    else
      render :new
    end
  end


  def edit
    @dimention = Dimention.find(params[:id])
  end

  def update
    @dimention = Dimention.find(params[:id])

      if @dimention.update(dimentions_params)
        redirect_to dimentions_path,
          flash: {notice: "Priority successfully edited"}
      else
        render :edit
      end
  end

  def destroy
    @dimention = Dimention.find(params[:id])

    @dimention.destroy
    redirect_to dimentions_path, flash: {notice: "Priority successfully deleted"}

  end

  def show
    @dimention = Dimention.find(params[:id])
  end



  private
    def dimentions_params
      params.require(:dimention).permit!
    end

end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController

  def index

    @factors = Factor.includes(:dimention).order(dimention_id: :asc ,weight: :desc)

    if params[:keyword].present?
      q = params[:keyword]
      @factors = @factors.joins(:dimention)
        .where("dimentions.title LIKE '%#{q}%' OR factors.title LIKE '%#{q}%'")
    end

    if request.xhr?
      render partial: "table", locals: {factors: @factors}
    end

  end

  def new
    @factor = Factor.new
  end

  def create
    @factor = Factor.new(factors_params)

    if @factor.save
      redirect_to factors_path,
        flash: {notice: "Factor successfully added"}
    else
      render :new
    end
  end


  def edit
    @factor = Factor.find(params[:id])
  end

  def update
    @factor = Factor.find(params[:id])

      if @factor.update(factors_params)
        redirect_to factors_path,
          flash: {notice: "Factor successfully edited"}
      else
        render :edit
      end
  end

  def destroy
    @factor = Factor.find(params[:id])

    @factor.destroy
    redirect_to factors_path, flash: {notice: "Factor successfully deleted"}

  end

  def show
    @factor = Factor.find(params[:id])
  end



  private
    def factors_params
      params.require(:factor).permit!
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout "external"

  def index
  end
end

app/helpers/amt_comments_helper.rb
module AmtCommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper



  def graphCategory
    @category = Priority.select(:title)

    @userlist = @category.map do |u|
        [u.title]
    end

    @userlist



  end

  def graphData


    @category = Priority.all
    @userlist = @category.map do |u|
      {:name => u.title, :data => u.dimentions.weigth, :pointPlacement =>"on"}
    end





    @userlist.to_json



  end




  def factorsCount
    Factor.count
  end

  def companiesCount
    Company.count
  end

  def technologiesCount
    Technology.count
  end

  def prioritiesCount
    Priority.count
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dimentions_helper.rb
module DimentionsHelper
end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/dimentions/_dimention.html.haml
%tr
  %td= dimention.priority.title
  %td= dimention.title
  %td= dimention.weight
  %td= link_to "Show", dimention_path(dimention)
  %td= link_to "Edit", edit_dimention_path(dimention)

app/views/dimentions/_form.html.haml
= render partial: "shared/print_errors", locals: {obj: @dimention}
= form_for @dimention do |f|
  .form-group
    %label Priority
    = f.collection_select :priority_id, Priority.order(:title), :id, :title, {}, :class => "form-control"
  .form-group
    %label Title
    = f.text_field :title, :class => "form-control"
  .form-group
    %label Weight
    = f.number_field :weight, :class => "form-control"
  .form-group
    = f.submit class: "button btn btn-primary"

app/views/dimentions/_table.html.haml
%table.table{"data-sortable" => "", "data-sortable-initialized" => "true"}
  %thead
    %tr
      %th Priority
      %th Title
      %th Weight
      %th Check Dimentions
      %th Edit
    %tbody
      = render dimentions

app/views/dimentions/edit.html.haml
.content
  .page-heading
  .row
    .col-sm-6.portlets
      .widget
        .widget-header.transparent
          %h2
            %strong Dimention
            Form
          .additional-btn
            %a.hidden.reload{:href => "#"}
              %i.icon-ccw-1
            %a.widget-toggle{:href => "#"}
              %i.icon-down-open-2
            %a.widget-close{:href => "#"}
              %i.icon-cancel-3
        .widget-content.padding
          = render partial: "shared/print_errors", locals: {obj: @dimention}
          = form_for @dimention do |f|
            .form-group
              %label Priority
              = f.collection_select :priority_id, Priority.order(:title), :id, :title, {}, :class => "form-control"
            .form-group
              %label Title
              = f.text_field :title, :class => "form-control"
            .form-group
              %label Weight
              = f.number_field :weight, :class => "form-control"
            .form-group
              = f.submit class: "button btn btn-primary"
              = link_to " Cancel", dimentions_path, class: "btn btn-primary", :style => "height: 34px;padding-top: 6px;"
              - if @dimention.factors.count==0
                = link_to " Delete Dimention", priority_path(@dimention), method: :delete, data: { confirm: "Are you Sure?" }, class: "btn btn-danger i fa fa-trash-o", :style => "height: 34px;padding-top: 8px;"

app/views/dimentions/index.html.haml
.widget
  .widget-header.transparent
    %h2
      %strong Dimention
      Table
    .additional-btn
      %a.hidden.reload{:href => "#"}
        %i.icon-ccw-1
  .widget-content
    .data-table-toolbar
      .row
        .col-md-4
          .toolbar-btn-action
            - if @dimentions.any?
              = render partial: "shared/filter_form", locals: {form_path: dimentions_path}
        .col-md-1
          .toolbar-btn-action
            = link_to " Add new", new_dimention_path, class: "a btn btn-success i fa fa-plus-circle"
    .table-responsive
      = render partial: "table", locals: {dimentions: @dimentions}

app/views/dimentions/new.html.haml
.content
  .page-heading
  .row
    .col-sm-6.portlets
      .widget
        .widget-header.transparent
          %h2
            %strong Dimention
            Form
          .additional-btn
            %a.hidden.reload{:href => "#"}
              %i.icon-ccw-1
            %a.widget-toggle{:href => "#"}
              %i.icon-down-open-2
            %a.widget-close{:href => "#"}
              %i.icon-cancel-3
        .widget-content.padding
          = render "form"

app/views/dimentions/show.html.haml
.widget
  .widget-header.transparent
    %h2
      %strong Dimention Selected
      Table

    .additional-btn
      %a.hidden.reload{:href => "#"}
        %i.icon-ccw-1
  .widget-content
    .data-table-toolbar
      .row
        .col-md-1
          .toolbar-btn-action
            = link_to " Back", dimentions_path, class: "btn btn-primary", :style => "height: 34px;padding-top: 6px;"
    .table-responsive
      = render partial: "table", locals: {dimentions: @dimention}


  .widget-header.transparent
    %h2
      %strong Factor for Dimention Selected
      Table
    .additional-btn
      %a.hidden.reload{:href => "#"}
        %i.icon-ccw-1
  .widget-content
    .table-responsive
      = form_for @dimention do |f|
        %table{"data-sortable" => "", "data-sortable-initialized" => "true"}
          %tr
            %th Title
            %th Weight
          = f.fields_for :factors do |order|
            %tr
              %td= order.text_field :title, readonly: true
              %td= order.text_field :weight, readonly: true