config/routes.rb
AMT::Application.routes.draw do

  get "amt_comments/index"
  get "priorities/index"

  root 'dashboard#index'

  resources :priorities  do
    resources :dimentions
  end

  resources :dimentions
  resources :factors

  resources :companies, except: [:show,:destroy]

  resources :amt_types do 
    resources :technologies, except: [:index]
  end 

  resources :technologies, only: [:index]

   resources :amt_comments 

end

app/models/amt_comment.rb
class AmtComment < ActiveRecord::Base
  belongs_to :technology
  belongs_to :user
end

app/models/amt_type.rb
class AmtType < ActiveRecord::Base
  validates_presence_of :title
  accepts_nested_attributes_for :technologies
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates_presence_of :name , :city
end

app/models/dimention.rb
class Dimention < ActiveRecord::Base
  belongs_to :priority
  has_many :factors
  validates_presence_of :title, :weight
  validates_numericality_of :weight, greater_than_or_equal_to: 0

  accepts_nested_attributes_for :factors

  def getId
    self.id
  end
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  belongs_to :dimention
  has_many :technologies



  accepts_nested_attributes_for :technologies

end

app/models/factor_survey_result.rb
class FactorSurveyResult < ActiveRecord::Base
  belongs_to :factor
  belongs_to :survey_result
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :dimentions
  validates_presence_of :title, :weight
  validates_numericality_of :weight, greater_than_or_equal_to: 0, less_than_or_equal_to: 100

  accepts_nested_attributes_for :dimentions



  

end

app/models/survey_result.rb
class SurveyResult < ActiveRecord::Base
  belongs_to :company
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates_presence_of :title ,:weight, :description, :benefits
  validates :summary, length: { maximum: 140 }

  belongs_to :factor
  belongs_to :amt_type
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :company
end

app/controllers/amt_types_controller.rb
class AmtTypesController < ApplicationController
  def index
    @amt_types = AmtType.order(:title)
  end

  def new
     @amt_types = AmtType.new
  end

  def create
    @amt_types = AmtType.new(amt_types_params)

    if @amt_types.save
      redirect_to amt_types_path, 
        flash: {notice: "AmtType successfully added"}
    else
      render :new
    end
  end

  def edit
    @amt_types = AmtType.find(params[:id])
  end

  def update
    @amt_types = AmtType.find(params[:id])

    if @amt_types.update(amt_types_params)
      redirect_to amt_types_path, 
        flash: {notice: "AmtType successfully edited"}
    else
      render :edit
    end
  end

  def show
    @amt_types = AmtType.find(params[:id])
  end

  private

    def amt_types_params
      params.require(:amt_type).permit!
    end
end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController

  def index

    @factors = Factor.includes(:dimention).order(dimention_id: :asc ,weight: :desc)

    if params[:keyword].present?
      q = params[:keyword]
      @factors = @factors.joins(:dimention)
        .where("dimentions.title LIKE '%#{q}%' OR factors.title LIKE '%#{q}%'")
    end

    if request.xhr?
      render partial: "table", locals: {factors: @factors}
    end

  end

  def new
    @factor = Factor.new
  end

  def create
    @factor = Factor.new(factors_params)

    if @factor.save
      redirect_to factors_path,
        flash: {notice: "Factor successfully added"}
    else
      render :new
    end
  end


  def edit
    @factor = Factor.find(params[:id])
  end

  def update
    @factor = Factor.find(params[:id])

      if @factor.update(factors_params)
        redirect_to factors_path,
          flash: {notice: "Factor successfully edited"}
      else
        render :edit
      end
  end

  def destroy
    @factor = Factor.find(params[:id])

    @factor.destroy
    redirect_to factors_path, flash: {notice: "Factor successfully deleted"}

  end

  def show
    @factor = Factor.find(params[:id])
  end



  private
    def factors_params
      params.require(:factor).permit!
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout "external"

  def index
  end
end

app/helpers/amt_comments_helper.rb
module AmtCommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper



  def graphCategory
    @category = Priority.select(:title)

    @userlist = @category.map do |u|
        [u.title]
    end

    @userlist



  end

  def graphData


    @category = Priority.all
    @userlist = @category.map do |u|
      {:name => u.title, :data => u.dimentions.weigth, :pointPlacement =>"on"}
    end





    @userlist.to_json



  end




  def factorsCount
    Factor.count
  end

  def companiesCount
    Company.count
  end

  def technologiesCount
    Technology.count
  end

  def prioritiesCount
    Priority.count
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dimentions_helper.rb
module DimentionsHelper
end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/amt_types/_amt_type.html.haml
%tr
  %td= amt_type.title
  %td= link_to "Show", amt_type_path(amt_type)
  %td= link_to "Edit", edit_amt_type_path(amt_type)

app/views/amt_types/_form.html.haml
= form_for @amt_types do |f|
  
  .widget
    .widget-header.transparent
      %h2
        %strong AMT Type
        Form
      
      .form-group
        .field
          .label
            = f.label :title
          = f.text_field :title, :class => "form-control"


      .actions
        = f.submit 'Save'

app/views/amt_types/edit.html.haml
.content
  .page-heading
  .row
    .col-sm-6.portlets    
      .widget
        .widget-header.transparent
          %h2
            %strong AMT Type
            Form
          .additional-btn
            %a.hidden.reload{:href => "#"}
              %i.icon-ccw-1
            %a.widget-toggle{:href => "#"}
              %i.icon-down-open-2
            %a.widget-close{:href => "#"}
              %i.icon-cancel-3
        .widget-content.padding
        

          = form_for @amt_types  do |a|
            .form-group
              %label Title
              = a.text_field :title, :class => "form-control"
            
            .form-group
              = a.submit class: "button btn btn-primary"

app/views/amt_types/index.html.haml
.row
  .col-md-12
    .widget
      .widget-header.transparent
        %h2
          %strong AMT Type
           
        .additional-btn
          %a.hidden.reload{:href => "#"}
            %i.icon-ccw-1
          %a.widget-toggle{:href => "#"}
            %i.icon-down-open-2
          %a.widget-close{:href => "#"}
            %i.icon-cancel-3
      .widget-content
        .data-table-toolbar
          .row
            .col-md-1
              .toolbar-btn-action
                = link_to ' Add New', new_amt_type_path ,class: "a btn btn-success i fa fa-plus-circle "
     
        .table-responsive
          %table.table.table-hover.table-striped{"data-sortable" => ""}
            %thead
              %tr
                %th Title
                %th Check AMT&M 
                %th Edit
            %tbody
              = render @amt_types

app/views/amt_types/new.html.haml
.content
  .page-heading
  .row
    .col-sm-6.portlets    
      .widget
        .widget-header.transparent
          %h2
            %strong AMT Type
            Form
          .additional-btn
            %a.hidden.reload{:href => "#"}
              %i.icon-ccw-1
            %a.widget-toggle{:href => "#"}
              %i.icon-down-open-2
            %a.widget-close{:href => "#"}
              %i.icon-cancel-3
        .widget-content.padding
        

          = form_for @amt_types  do |a|
            .form-group
              %label Title
              = a.text_field :title, :class => "form-control"
            
            .form-group
              = a.submit class: "button btn btn-primary"

app/views/amt_types/show.html.haml
.widget
  .widget-header.transparent
    %h2
      %strong AMT Type Selected
      Table

    .additional-btn
      %a.hidden.reload{:href => "#"}
        %i.icon-ccw-1
  .widget-content
    .data-table-toolbar
      .row
        .col-md-1
          .toolbar-btn-action
            = link_to " Back", amt_types_path, class: "btn btn-primary", :style => "height: 34px;padding-top: 6px;"
  .table-responsive
    %table.table{"data-sortable" => "", "data-sortable-initialized" => "true"}
      %thead
        %tr
          %th Title
          %th Check AMT&M 
          %th Edit
      %tbody
        = render @amt_types


  .widget-header.transparent
    %h2
      %strong Technologies for Priority Selected
      Table
    .additional-btn
      %a.hidden.reload{:href => "#"}
        %i.icon-ccw-1
  .widget-content
    .table-responsive
      = form_for @amt_types do |f|
        %table{"data-sortable" => "", "data-sortable-initialized" => "true"}
          %tr
            %th Title
            %th Description
            %th Others
            %th Summary
            %th Weight

          = f.fields_for :technologies do |order|
            %tr
              %td= order.text_field :title, readonly: true
              %td= order.text_field :description, readonly: true
              %td= order.text_field :others, readonly: true
              %td= order.text_field :summary, readonly: true
              %td= order.text_field :weight, readonly: true
            